name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest # hoi

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/liftmate:latest -f API/Dockerfile .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/liftmate:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: LiftmateApi
        slot-name: production
        images: "tiesvreeswijk/LiftmateApi:latest"
        azure-rm-credentials: ${{ secrets.AZURE_CREDENTIALS }}
