name: Build and Deploy LiftmateAPI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/liftmateapi:latest -f API/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/liftmateapi:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Log in to Azure with Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "liftmateapi" # Name of your Azure App Service
        slot-name: "production" # Default deployment slot
        images: "${{ secrets.DOCKER_USERNAME }}/liftmateapi:latest"
